// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="wrapperSingle48,hls_ip_2016_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku060-ffva1156-2-i,HLS_INPUT_CLOCK=2.400000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.400000,HLS_SYN_LAT=33,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=6,HLS_SYN_FF=541,HLS_SYN_LUT=204}" *)

module wrapperSingle48 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        i_coefs_mantRe_address0,
        i_coefs_mantRe_ce0,
        i_coefs_mantRe_q0,
        i_coefs_mantRe_address1,
        i_coefs_mantRe_ce1,
        i_coefs_mantRe_q1,
        i_coefs_mantIm_address0,
        i_coefs_mantIm_ce0,
        i_coefs_mantIm_q0,
        i_coefs_mantIm_address1,
        i_coefs_mantIm_ce1,
        i_coefs_mantIm_q1,
        i_coefs_exp_address0,
        i_coefs_exp_ce0,
        i_coefs_exp_q0,
        i_coefs_exp_address1,
        i_coefs_exp_ce1,
        i_coefs_exp_q1,
        i_coefs_tonegroupId_address0,
        i_coefs_tonegroupId_ce0,
        i_coefs_tonegroupId_we0,
        i_coefs_tonegroupId_d0,
        i_coefs_tonegroupId_q0,
        i_coefs_tonegroupId_address1,
        i_coefs_tonegroupId_ce1,
        i_coefs_tonegroupId_we1,
        i_coefs_tonegroupId_d1,
        i_coefs_tonegroupId_q1,
        i_coefs_tonegroupIdWithoutDV_address0,
        i_coefs_tonegroupIdWithoutDV_ce0,
        i_coefs_tonegroupIdWithoutDV_we0,
        i_coefs_tonegroupIdWithoutDV_d0,
        i_coefs_tonegroupIdWithoutDV_q0,
        i_coefs_tonegroupIdWithoutDV_address1,
        i_coefs_tonegroupIdWithoutDV_ce1,
        i_coefs_tonegroupIdWithoutDV_we1,
        i_coefs_tonegroupIdWithoutDV_d1,
        i_coefs_tonegroupIdWithoutDV_q1,
        i_tonesDis_address0,
        i_tonesDis_ce0,
        i_tonesDis_q0,
        i_tonesDis_address1,
        i_tonesDis_ce1,
        i_tonesDis_q1,
        disturberIDs,
        victim,
        ToneNr
);

parameter    ap_ST_fsm_state1 = 2'b1;
parameter    ap_ST_fsm_state2 = 2'b10;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv16_0 = 16'b0000000000000000;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] i_coefs_mantRe_address0;
output   i_coefs_mantRe_ce0;
input  [31:0] i_coefs_mantRe_q0;
output  [2:0] i_coefs_mantRe_address1;
output   i_coefs_mantRe_ce1;
input  [31:0] i_coefs_mantRe_q1;
output  [2:0] i_coefs_mantIm_address0;
output   i_coefs_mantIm_ce0;
input  [31:0] i_coefs_mantIm_q0;
output  [2:0] i_coefs_mantIm_address1;
output   i_coefs_mantIm_ce1;
input  [31:0] i_coefs_mantIm_q1;
output  [2:0] i_coefs_exp_address0;
output   i_coefs_exp_ce0;
input  [15:0] i_coefs_exp_q0;
output  [2:0] i_coefs_exp_address1;
output   i_coefs_exp_ce1;
input  [15:0] i_coefs_exp_q1;
output  [2:0] i_coefs_tonegroupId_address0;
output   i_coefs_tonegroupId_ce0;
output   i_coefs_tonegroupId_we0;
output  [15:0] i_coefs_tonegroupId_d0;
input  [15:0] i_coefs_tonegroupId_q0;
output  [2:0] i_coefs_tonegroupId_address1;
output   i_coefs_tonegroupId_ce1;
output   i_coefs_tonegroupId_we1;
output  [15:0] i_coefs_tonegroupId_d1;
input  [15:0] i_coefs_tonegroupId_q1;
output  [2:0] i_coefs_tonegroupIdWithoutDV_address0;
output   i_coefs_tonegroupIdWithoutDV_ce0;
output   i_coefs_tonegroupIdWithoutDV_we0;
output  [15:0] i_coefs_tonegroupIdWithoutDV_d0;
input  [15:0] i_coefs_tonegroupIdWithoutDV_q0;
output  [2:0] i_coefs_tonegroupIdWithoutDV_address1;
output   i_coefs_tonegroupIdWithoutDV_ce1;
output   i_coefs_tonegroupIdWithoutDV_we1;
output  [15:0] i_coefs_tonegroupIdWithoutDV_d1;
input  [15:0] i_coefs_tonegroupIdWithoutDV_q1;
output  [2:0] i_tonesDis_address0;
output   i_tonesDis_ce0;
input  [63:0] i_tonesDis_q0;
output  [2:0] i_tonesDis_address1;
output   i_tonesDis_ce1;
input  [63:0] i_tonesDis_q1;
input  [31:0] disturberIDs;
input  [31:0] victim;
input  [31:0] ToneNr;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state1;
wire    grp_single_line_48dist_1_fu_26_ap_start;
wire    grp_single_line_48dist_1_fu_26_ap_done;
wire    grp_single_line_48dist_1_fu_26_ap_idle;
wire    grp_single_line_48dist_1_fu_26_ap_ready;
wire   [2:0] grp_single_line_48dist_1_fu_26_i_coefs_mantRe_address0;
wire    grp_single_line_48dist_1_fu_26_i_coefs_mantRe_ce0;
wire   [2:0] grp_single_line_48dist_1_fu_26_i_coefs_mantRe_address1;
wire    grp_single_line_48dist_1_fu_26_i_coefs_mantRe_ce1;
wire   [2:0] grp_single_line_48dist_1_fu_26_i_coefs_mantIm_address0;
wire    grp_single_line_48dist_1_fu_26_i_coefs_mantIm_ce0;
wire   [2:0] grp_single_line_48dist_1_fu_26_i_coefs_mantIm_address1;
wire    grp_single_line_48dist_1_fu_26_i_coefs_mantIm_ce1;
wire   [2:0] grp_single_line_48dist_1_fu_26_i_coefs_exp_address0;
wire    grp_single_line_48dist_1_fu_26_i_coefs_exp_ce0;
wire   [2:0] grp_single_line_48dist_1_fu_26_i_coefs_exp_address1;
wire    grp_single_line_48dist_1_fu_26_i_coefs_exp_ce1;
wire   [2:0] grp_single_line_48dist_1_fu_26_i_tonesDis_address0;
wire    grp_single_line_48dist_1_fu_26_i_tonesDis_ce0;
wire   [2:0] grp_single_line_48dist_1_fu_26_i_tonesDis_address1;
wire    grp_single_line_48dist_1_fu_26_i_tonesDis_ce1;
reg    ap_reg_grp_single_line_48dist_1_fu_26_ap_start;
wire   [0:0] ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'b1;
#0 ap_reg_grp_single_line_48dist_1_fu_26_ap_start = 1'b0;
end

single_line_48dist_1 grp_single_line_48dist_1_fu_26(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_single_line_48dist_1_fu_26_ap_start),
    .ap_done(grp_single_line_48dist_1_fu_26_ap_done),
    .ap_idle(grp_single_line_48dist_1_fu_26_ap_idle),
    .ap_ready(grp_single_line_48dist_1_fu_26_ap_ready),
    .i_coefs_mantRe_address0(grp_single_line_48dist_1_fu_26_i_coefs_mantRe_address0),
    .i_coefs_mantRe_ce0(grp_single_line_48dist_1_fu_26_i_coefs_mantRe_ce0),
    .i_coefs_mantRe_q0(i_coefs_mantRe_q0),
    .i_coefs_mantRe_address1(grp_single_line_48dist_1_fu_26_i_coefs_mantRe_address1),
    .i_coefs_mantRe_ce1(grp_single_line_48dist_1_fu_26_i_coefs_mantRe_ce1),
    .i_coefs_mantRe_q1(i_coefs_mantRe_q1),
    .i_coefs_mantIm_address0(grp_single_line_48dist_1_fu_26_i_coefs_mantIm_address0),
    .i_coefs_mantIm_ce0(grp_single_line_48dist_1_fu_26_i_coefs_mantIm_ce0),
    .i_coefs_mantIm_q0(i_coefs_mantIm_q0),
    .i_coefs_mantIm_address1(grp_single_line_48dist_1_fu_26_i_coefs_mantIm_address1),
    .i_coefs_mantIm_ce1(grp_single_line_48dist_1_fu_26_i_coefs_mantIm_ce1),
    .i_coefs_mantIm_q1(i_coefs_mantIm_q1),
    .i_coefs_exp_address0(grp_single_line_48dist_1_fu_26_i_coefs_exp_address0),
    .i_coefs_exp_ce0(grp_single_line_48dist_1_fu_26_i_coefs_exp_ce0),
    .i_coefs_exp_q0(i_coefs_exp_q0),
    .i_coefs_exp_address1(grp_single_line_48dist_1_fu_26_i_coefs_exp_address1),
    .i_coefs_exp_ce1(grp_single_line_48dist_1_fu_26_i_coefs_exp_ce1),
    .i_coefs_exp_q1(i_coefs_exp_q1),
    .i_tonesDis_address0(grp_single_line_48dist_1_fu_26_i_tonesDis_address0),
    .i_tonesDis_ce0(grp_single_line_48dist_1_fu_26_i_tonesDis_ce0),
    .i_tonesDis_q0(i_tonesDis_q0),
    .i_tonesDis_address1(grp_single_line_48dist_1_fu_26_i_tonesDis_address1),
    .i_tonesDis_ce1(grp_single_line_48dist_1_fu_26_i_tonesDis_ce1),
    .i_tonesDis_q1(i_tonesDis_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_single_line_48dist_1_fu_26_ap_start <= 1'b0;
    end else begin
        if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
            ap_reg_grp_single_line_48dist_1_fu_26_ap_start <= 1'b1;
        end else if ((1'b1 == grp_single_line_48dist_1_fu_26_ap_ready)) begin
            ap_reg_grp_single_line_48dist_1_fu_26_ap_start <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ~(1'b0 == grp_single_line_48dist_1_fu_26_ap_done))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ~(1'b0 == grp_single_line_48dist_1_fu_26_ap_done))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (~(1'b0 == grp_single_line_48dist_1_fu_26_ap_done)) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[ap_const_lv32_0];

assign ap_CS_fsm_state2 = ap_CS_fsm[ap_const_lv32_1];

assign grp_single_line_48dist_1_fu_26_ap_start = ap_reg_grp_single_line_48dist_1_fu_26_ap_start;

assign i_coefs_exp_address0 = grp_single_line_48dist_1_fu_26_i_coefs_exp_address0;

assign i_coefs_exp_address1 = grp_single_line_48dist_1_fu_26_i_coefs_exp_address1;

assign i_coefs_exp_ce0 = grp_single_line_48dist_1_fu_26_i_coefs_exp_ce0;

assign i_coefs_exp_ce1 = grp_single_line_48dist_1_fu_26_i_coefs_exp_ce1;

assign i_coefs_mantIm_address0 = grp_single_line_48dist_1_fu_26_i_coefs_mantIm_address0;

assign i_coefs_mantIm_address1 = grp_single_line_48dist_1_fu_26_i_coefs_mantIm_address1;

assign i_coefs_mantIm_ce0 = grp_single_line_48dist_1_fu_26_i_coefs_mantIm_ce0;

assign i_coefs_mantIm_ce1 = grp_single_line_48dist_1_fu_26_i_coefs_mantIm_ce1;

assign i_coefs_mantRe_address0 = grp_single_line_48dist_1_fu_26_i_coefs_mantRe_address0;

assign i_coefs_mantRe_address1 = grp_single_line_48dist_1_fu_26_i_coefs_mantRe_address1;

assign i_coefs_mantRe_ce0 = grp_single_line_48dist_1_fu_26_i_coefs_mantRe_ce0;

assign i_coefs_mantRe_ce1 = grp_single_line_48dist_1_fu_26_i_coefs_mantRe_ce1;

assign i_coefs_tonegroupIdWithoutDV_address0 = ap_const_lv3_0;

assign i_coefs_tonegroupIdWithoutDV_address1 = ap_const_lv3_0;

assign i_coefs_tonegroupIdWithoutDV_ce0 = 1'b0;

assign i_coefs_tonegroupIdWithoutDV_ce1 = 1'b0;

assign i_coefs_tonegroupIdWithoutDV_d0 = ap_const_lv16_0;

assign i_coefs_tonegroupIdWithoutDV_d1 = ap_const_lv16_0;

assign i_coefs_tonegroupIdWithoutDV_we0 = 1'b0;

assign i_coefs_tonegroupIdWithoutDV_we1 = 1'b0;

assign i_coefs_tonegroupId_address0 = ap_const_lv3_0;

assign i_coefs_tonegroupId_address1 = ap_const_lv3_0;

assign i_coefs_tonegroupId_ce0 = 1'b0;

assign i_coefs_tonegroupId_ce1 = 1'b0;

assign i_coefs_tonegroupId_d0 = ap_const_lv16_0;

assign i_coefs_tonegroupId_d1 = ap_const_lv16_0;

assign i_coefs_tonegroupId_we0 = 1'b0;

assign i_coefs_tonegroupId_we1 = 1'b0;

assign i_tonesDis_address0 = grp_single_line_48dist_1_fu_26_i_tonesDis_address0;

assign i_tonesDis_address1 = grp_single_line_48dist_1_fu_26_i_tonesDis_address1;

assign i_tonesDis_ce0 = grp_single_line_48dist_1_fu_26_i_tonesDis_ce0;

assign i_tonesDis_ce1 = grp_single_line_48dist_1_fu_26_i_tonesDis_ce1;

endmodule //wrapperSingle48
